version: '3.8'

services:
  frontend:
    build: my-app
    ports:
      - "3000:80"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rnative
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=rnative
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rnative
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adapters:
    image: rnapdbee-adapters-image
    environment:
      - ADAPTERS_WORKERS=24
      - ADAPTERS_THREADS=1
      - ADAPTERS_WORKER_TIMEOUT=1200
      - ADAPTERS_MAX_REQUESTS=10
      - ADAPTERS_GUNICORN_LOG_LEVEL=info
      - ADAPTERS_CACHE_DIR=/var/tmp/adapters_cache
      - ADAPTERS_CACHE_THRESHOLD=50
      - ADAPTERS_CACHE_TIMEOUT=3600
      - ADAPTERS_SUBPROCESS_TIMEOUT=600
      - ADAPTERS_PSEUDOVIEWER_TIMEOUT=40
      - ADAPTERS_FLASK_LOG_LEVEL=INFO
    volumes:
      - adapters_cache:/var/tmp/adapters_cache
    ports:
      - "8000:80"

volumes:
  postgres_data:
  adapters_cache:
