services:
  frontend:
    build:
      args:
        - REACT_APP_SERVER_ADDRESS=http://localhost/api/compute

  backend:
    volumes:
      - /mnt:/mnt

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/local/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - adapters
    command: nginx -g "daemon off;"

  # Remove HTTPS-related services that aren't needed locally
  certbot:
    profiles:
      - production
