services:
  frontend:
    build:
      context: my-app
      args:
        - REACT_APP_SERVER_ADDRESS=http://localhost/api/compute

  app:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rnative
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=rnative
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=rnative
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adapters:
    image: rnapdbee-adapters-image
    environment:
      - ADAPTERS_WORKERS=6
      - ADAPTERS_THREADS=1
      - ADAPTERS_WORKER_TIMEOUT=1200
      - ADAPTERS_MAX_REQUESTS=10
      - ADAPTERS_GUNICORN_LOG_LEVEL=info
      - ADAPTERS_CACHE_DIR=/var/tmp/adapters_cache
      - ADAPTERS_CACHE_THRESHOLD=50
      - ADAPTERS_CACHE_TIMEOUT=3600
      - ADAPTERS_SUBPROCESS_TIMEOUT=600
      - ADAPTERS_PSEUDOVIEWER_TIMEOUT=40
      - ADAPTERS_FLASK_LOG_LEVEL=INFO
    volumes:
      - adapters_cache:/var/tmp/adapters_cache

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - app
      - adapters

volumes:
  postgres_data:
  adapters_cache:
